services:
  maths:
    # use `docker compose up` to pull/use prebuilt image
    image: ghcr.io/qincai-rui/maths:latest

    # use `docker compose up --build` to build the image locally
    build: .
    ports:
      - "5185:5185"
    environment:
      - PORT=5185
      - HOST=0.0.0.0
    restart: unless-stopped
